services:
  database:
    build: ./database
    container_name: postgres-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend-simple-api
    container_name: springboot-api
    depends_on:
      - database
    networks:
      - app-network
    ports:
      - "8080:8080"

  httpd:
    build: ./http
    container_name: apache-reverse-proxy
    ports:
      - "8088:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data: