spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/db
    username: usr
    password: pwd

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect